name: 'create azure resources'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'the Github Environment that specifies where to delete Azure resources.'
        type: environment
        required: true

jobs:
  delete-azure-infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v3