name: 'create azure resources'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'the Github Environment that specifies where to create the Azure resources.'
        type: environment
        required: true
      numberOfAzureUsers:
        description: 'the number of Azure users to create.'
        type: number
        required: false
        default: 1

jobs:
  create-azure-infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      
      - name: Setup Azure Environment
        uses: azure/powershell@v2
        with:
          inlineScript: |
            $azModule = Get-InstalledModule -Name Az
            Write-Host "Az version $($azModule.Version)"
            if ([string]::IsNullOrEmpty("${{ secrets.PASSWORD }}")) {
              Write-Error "Password is null or empty. Please specify a password and try again."
              exit 1
            }

            ./azure-integration/infrastructure/scripts/setup-azure.ps1 -NumberOfUsers "${{ inputs.numberOfAzureUsers }}" `
              -BillingString "${{ secrets.BILLING_STRING }}" `
              -Password $(ConvertTo-SecureString -AsPlainText -Force "${{ secrets.PASSWORD }}") `
              -DomainName "${{ vars.DOMAIN_NAME }}"
          azPSVersion: 'latest'
