name: 'create azure resources'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'the Github Environment that specifies where to delete Azure resources.'
        type: environment
        required: true