name: 'delete azure resources'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'the Github environment that specifies where to delete the Azure resources.'
        type: environment
        required: true

jobs:
  delete-azure-infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    container:
      image: mcr.microsoft.com/azure-powershell:11.5.0-ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Login To Azure
        shell: pwsh
        run: |
          $credentials = ConvertFrom-Json -InputObject ${{ secrets.AZURE_CREDENTIALS }}
          $securePassword = $credentials.clientSecret | ConvertTo-SecureString -AsPlainText -Force
          $pscredential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $credentials.clientId, $securePassword
          Connect-AzAccount -ServicePrincipal -Credential $pscredential -Tenant $credentials.tenantId
      
      - name: Teardown Azure Environment
        shell: pwsh
        working-directory: ./azure-integration/infrastructure/scripts
        run: |
          ./tear-down-azure.ps1
