name: 'delete azure resources'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'the Github environment that specifies where to delete the Azure resources.'
        type: environment
        required: true

jobs:
  delete-azure-infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    container:
      image: mcr.microsoft.com/azure-powershell:11.5.0-ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      
      - name: Teardown Azure Environment
        shell: pwsh
        working-directory: ./azure-integration/infrastructure/scripts
        run: |
          ./tear-down-azure.ps1
