name: 'create azure resources'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'the Github Environment that specifies where to create the Azure resources.'
        type: environment
        required: true
      numberOfAzureUsers:
        description: 'the number of Azure users to create.'
        type: number
        required: false
        default: 1

jobs:
  create-azure-infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      
      - id: setup-azure
        name: Setup Azure Environment
        uses: azure/powershell@v2
        with:
          inlineScript: |
            $password = ConvertTo-SecureString -String "${{ secrets.AZURE_USER_PASSWORD }}" -AsPlainText -Force
            $resourceGroups = ./azure-integration/infrastructure/scripts/setup-azure.ps1 `
              -NumberOfUsers "${{ inputs.numberOfAzureUsers }}" `
              -DomainName "${{ vars.AZURE_DOMAIN_NAME }}" `
              -Password $password `
              -OwnerId "${{ secrets.AZURE_OWNER_ID }}" `
              -SubscriptionId "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
              -DefaultResourceGroup "${{ vars.AZURE_RESOURCE_GROUP }}"
            "RESOURCE_GROUPS=$resourceGroups | Out-File -FilePath $env:GITHUB_OUTPUT -Append"
            echo $resourceGroups >> "$GITHUB"
          azPSVersion: 'latest'

      - name: Deploy Bicep file
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP }}
          template: ./azure-integration/infrastructure/bicep/main.bicep
          parameters: |
            'resourceGroups=${{ steps.setup-azure.outputs.RESOURCE_GROUPS }} 
            adminPassword=${{ secrets.AZURE_USER_PASSWORD }}'
          failOnStdErr: false
