name: 'delete azure resources'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'the Github environment that specifies where to delete the Azure resources.'
        type: environment
        required: true

jobs:
  delete-azure-infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          
      - name: Teardown Azure Environment
        uses: azure/powershell@v2
        with:
          inlineScript: |
            ./azure-integration/infrastructure/scripts/tear-down-azure.ps1 `
              -SubscriptionId "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          azPSVersion: 'latest'
